# Generated by Django 4.1.7 on 2023-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('qty', models.IntegerField(default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='post_images')),
            ],
        ),
    ]
