# Generated by Django 4.1.7 on 2023-06-11 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0005_alter_item_price_alter_item_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
