# Generated by Django 4.1.7 on 2023-06-17 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0007_alter_item_price_alter_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
